"""db model update

Revision ID: d91a9c63da8e
Revises: 93fda42d43ff
Create Date: 2020-02-09 20:19:41.254720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91a9c63da8e'
down_revision = '93fda42d43ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('idgroup', sa.Integer(), nullable=False),
    sa.Column('groupname', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.iduser'], ),
    sa.PrimaryKeyConstraint('idgroup')
    )
    op.create_index(op.f('ix_group_groupname'), 'group', ['groupname'], unique=False)
    op.create_table('result',
    sa.Column('idresults', sa.Integer(), nullable=False),
    sa.Column('filetype', sa.String(length=45), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('date_upload', sa.DateTime(), nullable=True),
    sa.Column('date_modif', sa.DateTime(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.idgroup'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.iduser'], ),
    sa.PrimaryKeyConstraint('idresults')
    )
    op.create_index(op.f('ix_result_content'), 'result', ['content'], unique=False)
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['iduser'])
    op.add_column('user', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('iduser', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'group', ['group_id'], ['idgroup'])
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'iduser')
    op.drop_column('user', 'group_id')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_result_content'), table_name='result')
    op.drop_table('result')
    op.drop_index(op.f('ix_group_groupname'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
