"""adding researchfield

Revision ID: dc4bd38b64ec
Revises: f6cd847e50ff
Create Date: 2020-03-16 12:33:35.731521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc4bd38b64ec'
down_revision = 'f6cd847e50ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('researchfield', sa.String(length=255), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_field_researchfield'), 'research_field', ['researchfield'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_field_researchfield'), table_name='research_field')
    op.drop_table('research_field')
    # ### end Alembic commands ###
